app/app/urls.py
from django.contrib import admin

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app/main/urls.py
from django.urls import path
from django.conf.urls.static import static
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name = 'index'),
    path('catalog/', views.CatalogView.as_view(), name= 'catalog'),
    path('catalog/<slug:category_slug>', views.ProductDetailView.as_view(), name = 'product_detail'),
    path('about/', views.AboutView.as_view(), name='about_page'),
]

app/main/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.CharField(max_length=200, unique=True)
    
    def save(self,*args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)
        
    def __str__(self):
        return self.name
    
class Size(models.Model):
    name = models.CharField(max_length=20)
    
    class Meta:
        db_table = 'Size'
        verbose_name = 'Размер'
        verbose_name_plural = 'Размеры'
        
    def __str__(self):
        return self.name
    
class ProductSize(models.Model):
    size = models.ForeignKey(Size, on_delete=models.Model, related_name='sizes')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='productsize')

class Product(models.Model):
    name = models.CharField(max_length=100)
    slug = models.CharField(max_length=200, unique=True)
    #price = models.DecimalField(max_digits=10, decimal_places=2) пусть будет цена будет привязана к цене
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    image = models.ImageField(upload_to='product/main/', null=True)
    description = models.TextField(blank=True)
    
    class Meta:
        db_table = 'Product'
        verbose_name = 'продукт'
        verbose_name_plural = 'Продукты'
    
    def save(self,*args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)
        
    def __str__(self):
        return self.name

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                related_name='images')
    image = models.ImageField(upload_to='product/extra/')

app/main/views.py
from django.views.generic import TemplateView, DetailView
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.template.response import TemplateResponse
from .models import Category, Product, Size
from django.db.models import Q

# Create your views here.
class IndexView(TemplateView): #посути метод получения данных
    template_name = 'main/base.html' #базовая верстка, чьи элементы можно менять
    
    def get_context_data(self, **kwargs): #получения данных
        context = super().get_context_data(**kwargs) #получения аргументов
        context['categories'] = Category.objects.all() # получение всех объектов класс
        context['current_category'] = None #всегда остается пустым
        return context
    
    def get(self, request, *args, **kwargs): #цель функции проверить, существует ли товар
        context = self.get_context_data(**kwargs) #передаем данные
        if request.headers.get('HX-Request'): #если это HTMX запрос
            return TemplateResponse(request, 'main/home_content.html', context) #если да, то выводим блок
        return TemplateResponse(request, self.template_name, context) #выводим страницу, всегда
    
class CatalogView(TemplateView):
    template_name = 'main/catalog.html'
    
    FILTER_MAPPING = { #короче это фильтер, лямбда нужна что бы проебашить все объекты
    'name': lambda queryset, value: queryset.filter(name__iexact=value), #предписка i-что-то, нужна для игнорирования реестра
    'price': lambda queryset, value: queryset.filter(price__gte=value),
    'max_price': lambda queryset, value: queryset.filter(price__lte=value),
    'description': lambda queryset, value: queryset.filter(description__icontains=value),
    'desc_start': lambda queryset, value: queryset.filter(description__istartswith=value), #типо поиск по первому слову, ну удобно хули
    }
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug = kwargs.get('category_slug')
        current_category = None #выбраная категория типа
        products = Product.objects.all()# Фильтруем по категории, сюда можно впихнуть фильтр по дате, но похуй
        categories = Category.objects.all() #берем все категории
        
        if slug:
            current_category = get_object_or_404(Category, slug = slug)
            products = products.filter(Category=slug)
            
        query = self.request.GET.get('q')
        if query:
            products = products.filter(
                Q(name__icontains = query) | Q(description__incontains = query)
            )
        filter_params = {} #инициализируем словарь, что бы был
        for param, filter_func in self.FILTER_MAPPING.items():
            value = self.request.GET.get(param)
            if value:
                products = filter_func(products,value)
                filter_params[param] = value
            else:
                filter_params[param] = ''
                
        filter_params['q'] = query or ''
        
        context.update({
            'categories' : categories,
            'products' : products,
            'current_category': slug,
            'filter_params': filter_params,
            #'sizes': Size.objects.all(), такую конструкцию можно использовать для доп объектов или конструкций
            'search_query': query or ''
        })
        
        if self.request.GET.get('slow_search') == 'true': #короче, наш поисковик
            context['show_search'] = True
        elif self.request.GET.get('reset_search') == 'true':
            context['reset_search'] = True
            
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        if request.headers.get('HX-Request'):
            return TemplateResponse(request, 'main/product_list.html', context)
        return TemplateResponse(request, self.template_name, context)
    
class ProductDetailView(DetailView):
    model = Product
    template_name = 'main/base.html'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.get_object()
        context['categories'] = Category.objects.all()
        context['related_product'] = Product.objects.filter(
            Category=product.category
        ).exclude(id=product.id)[:4]
        context['current_category'] = product.category.slug
        return context
    
    def get(self, request, *args, **kwargs): #цель функции проверить, существует ли товар
        context = self.get_context_data(**kwargs) #передаем данные
        if request.headers.get('HX-Request'): #если это HTMX запрос
            return TemplateResponse(request, 'main/home_content.html', context) #если да, то выводим блок
        return TemplateResponse(request, self.template_name, context) #выводим страницу, всегда
    
class AboutView(TemplateView): #посути блок, ыыы
    template_name = 'main/about.html'  # Полная страница

    def get(self, request, *args, **kwargs):
        # Если прилетел запрос от HTMX (например, нажали на ссылку в меню)
        if request.headers.get('HX-Request'):
            # Отдаем ТОЛЬКО кусок с контентом
            return TemplateResponse(request, 'main/about_content.html')
        # Если юзер просто вбил адрес в строку или обновил страницу (F5)
        return super().get(request, *args, **kwargs)

app/main/templates/main/about.html
{% extends "main/base.html" %}

{% block content %}
<div class="my-5 pt-5 px-2 pb-2 bg-white custom-shadow rounded">
    <h2 class="m-2"><strong>О нас</strong></h2>
    <p class="m-2" style="font-size: 1.2rem;">Текст о том какой классный этот интернет магазин.</p>
</div>
{% endblock %}

{% block title%}
    О нас
{% endblock title%}

app/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>
    {% block title %}
        Главная
    {% endblock title %}
    </title>
    {% block begin %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
    <!-- Стиль footer-a для главной страницы -->
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
    <!-- Favicons for different platforms -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "deps/favicon/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "deps/favicon/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "deps/favicon/site.webmanifest" %}">
    {% endblock begin %}
</head>



<body>
    {% block menu %}
        <header>
            <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
                <div class="container">
                    <a class="navbar-brand" href="index.html">Home</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item dropdown ">
                                <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    Информация
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item  text-white" href="#">Доставка и оплата</a></li>
                                    <li><a class="dropdown-item  text-white" href="#">Контактная информация</a></li>
                                    <li><a class="dropdown-item  text-white" href="{% url 'main:about_page' %}" hx-get="{% url 'main:about_page' %}" hx-target="#main-content" hx-push-url="true">О нас</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link  text-white" href="carts/cart.html">Корзина</a>
                            </li>
                                <li class="nav-item"><a class="nav-link  text-white" href="users/login.html">Войти</a></li>
                            <li class="nav-item dropdown ">
                                <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    Мой профиль
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item  text-white" href="carts/cart.html">Корзина</a></li>
                                    <li><a class="dropdown-item  text-white" href="users/profile.html">Личный кабинет</a></li>
                                    <li><a class="dropdown-item  text-white" href="{% url 'admin:index' %}">Админ панель</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item  text-white" href="#">Выйти</a></li>
                                </ul>
                            </li>
                        </ul>
                        <form class="d-flex" role="search">
                            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
                        </form>
                    </div>
                </div>
            </nav>
        </header>
    {% endblock menu %}
    <section>
        <div class="container">
            <!-- Каталог и корзина с фиксированным расположением на странице -->
            <div class="row mt-1 position-fixed z-3">
                <!-- Каталог -->
                {% block listgategories%}
                    <div class="dropdown mb-2">
                        <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Каталог
                            <img class="mx-1" src="{% static "deps/icons/grid-fill.svg" %}" alt="Catalog Icon" width="16"
                                height="16">
                        </button>
                        <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                            <li><a class="dropdown-item text-white" href="{% url 'main:catalog' %}">Все товары</a></li>
                            {% for a in categories %}
                                <li><a class="dropdown-item text-white" href="{% url 'main:catalog'%}">{{a.name}}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endblock listgategories%}
                <!-- Значек корзины, вызывает модальное окно -->
                {%block basket%}
                    <div>
                        <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
                            aria-expanded="false">
                            <img class="mx-1" src="{% static "deps/icons/basket2-fill.svg" %}" alt="Catalog Icon" width="24"
                                height="24">
                            <span id="goods-in-cart-count">0</span>
                        </button>
                    </div>
                    <!-- Разметка модального окна корзины -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                        aria-hidden="true">
                        <div class="modal-dialog modal-dialog-scrollable">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <h3 class="text-center mb-4">Корзина</h3>
                                    <div class="container" id="cart-items-container">
                                        <!-- Разметка корзины -->
                                        <div class="card mb-3 text-bg-light shadow-lg">
                                            <div class="card-header">
                                                <h5 class="card-title">Товар</h5>
                                            </div>
                                            <ul class="list-group list-group-flush">
                                                <li class="list-group-item">
                                                    <div class="row text-center">
                                                        <div class="col p-0">
                                                            <div class="input-group">
                                                                <span class="input-group-btn">
                                                                    <button type="button" class="btn btn-dark btn-sm decrement"
                                                                        data-cart-id="" data-cart-change-url="">-</button>
                                                                </span>
                                                                <input type="text" class="form-control number" value="1"
                                                                    readonly>
                                                                <span class="input-group-btn">
                                                                    <button type="button" class="btn btn-dark btn-sm increment"
                                                                        data-cart-id="" data-cart-change-url="">+</button>
                                                                </span>
                                                            </div>
                                                        </div>
                                                        <div class="col p-0">
                                                            <p>x 100.00 = </p>
                                                        </div>
                                                        <div class="col p-0"><strong>100.00 $</strong></div>
                                                        <div class="col p-0">
                                                            <a href="#" class="remove-from-cart" data-cart-id="">
                                                                <img class="mx-1" src="{% static "deps/icons/trash3-fill.svg" %}"
                                                                    alt="Catalog Icon" width="16" height="16">
                                                            </a>
                                                        </div>
                                                    </div>
                                                </li>
                                            </ul>
                                        </div>
                                        <div class="card mb-3 shadow-lg">
                                            <div class="card-footer">
                                                <p class="float-left">Итого <strong>1</strong> товар(а) на сумму</p>
                                                <h4 class="float-left"><strong>100.00 $</strong></h4>
                                            </div>
                                        </div>
                                    <!-- Закончилась разметка корзины -->
                                </div>
                                <a class="btn btn-dark" href="orders/create_order.html">
                                    Оформить заказ
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                {%endblock basket%}
                <!-- Закончилась разметка модального окна -->
            </div>
        </div>
        <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    <h1 class="mt-5 pt-5"><strong>
                        {% block content %}
                            <h1 class="mt-5 pt-5">Магазин мебели HOME<strong>
                        {% endblock content %}

                        {% block pagenation %}
                        {% endblock pagenation %}
                    </strong></h1>
                </div>
            </div>
        </div>
    </section>
    <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">вы нашли ошибку? расскажите об этом вашей маме!</p>
        </div>
    </footer>
    <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "deps/js/jquery-events.js" %}"></script>
    <script src="{% static "deps/js/jquery-ajax.js" %}"></script>
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
</body>

</html>

app/main/templates/main/catalog.html
{% extends "main/base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    {% block title%}
        Каталог
    {% endblock title%}

    {% block begin %}
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
        <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
        <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
        <link rel="apple-touch-icon" sizes="180x180" href="{% static "deps/favicon/apple-touch-icon.png" %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/favicon-32x32.png" %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static "deps/favicon/favicon-16x16.png" %}">
        <link rel="manifest" href="{% static "deps/favicon/site.webmanifest" %}">
    {% endblock begin %}
</head>

<body>
    <section>
        <div class="container">
        <!-- Контент -->
        {% block content%}
            <div class="container">
                <div class="row mt-1">
                    <div class="col-lg-2">
                        <!-- Пустой блок на усмотрение -->
                    </div>
                    <div class="col-lg-10">
                        <!-- Контент на странице -->
                        <div class="row">
                            <!-- Форма фильтров -->
                            {% block filter  %}
                                <div class="dropdown mb-2">
                                <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                    Фильтры
                                </button>
                        
                                <form action="" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
                                    <div class="form-check text-white mx-3">
                                        <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on">
                                        <input type="hidden" name="q" value="request.GET.q">
                                        <label class="form-check-label" for="flexCheckDefault">
                                            Товары по акции
                                        </label>
                                    </div>
                                    <p class="text-white mx-3 mt-3">Сортировать:</p>
                                    <div class="form-check text-white mx-3">
                                        <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default" checked>
                                        <label class="form-check-label" for="flexRadioDefault1">
                                            По умолчанию
                                        </label>
                                    </div>
                                    <div class="form-check text-white mx-3">
                                        <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price">
                                        <label class="form-check-label" for="flexRadioDefault2">
                                            От дешевых к дорогим
                                        </label>
                                    </div>
                                    <div class="form-check text-white mx-3">
                                        <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price">
                                        <label class="form-check-label" for="flexRadioDefault3">
                                            От дорогих к дешевым
                                        </label>
                                    </div>
                                    <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
                                </form>
                            </div>
                            {% endblock filter %}
                            
                            <!-- Карта товара -->
                            {% block goods %}
                                {% for a in Product%}
                                <div class="col-lg-4 col-md-6 p-4">
                                    <div class="card border-primary rounded custom-shadow">
                                        <img src="../deps/images/goods/double bed.jpg" class="card-img-top" alt="...">
                                        <div class="card-body">
                                            <a href="#">
                                                <p class="card-title">{{a.name}}</p>
                                            </a>
                                            <p class="card-text text-truncate">{{a.description}}</p>
                                            <p class="product_id">{{a.id}}</p>
                                            <div class="d-flex justify-content-between">
                                                <p><s>{{a.price}}</s> $</p>
                                                <!--<p><strong></strong></p>
                                                <span class="badge bg-warning text-dark">Скидка 10.00 %</span>-->
                                                <!-- <p><strong>100.00 $</strong></p> -->
                                                <a href="#" class="btn">
                                                    {% if product.image %}
                                                        <img src="{{ product.image.url }}" alt="{{ product.name }}" alt="Catalog Icon" width="32" height="32">
                                                    {% else %}
                                                        <img src="/static/images/no-image.png" alt="Нет фото">
                                                    {% endif %}
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            {% endblock goods %}
                    {% endblock content %}
                        <!-- Пагинация -->
                        {% block pagenation %}
                            <nav aria-label="Page navigation example">
                                <ul class="pagination justify-content-center my-4">
                                    <div class="custom-shadow d-flex">
                                        <li class="page-item disabled">
                                        <a class="page-link">Previous</a>
                                        </li>
                                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                                        <li class="page-item">
                                        <a class="page-link" href="#">Next</a>
                                        </li>
                                    </div>
                                </ul>
                            </nav>   
                        {% endblock pagenation %}
                        
                    </div>
                </div>
            </div>
    </section>
</body>

</html>